### ISSUE TITLE
tmpdir needs to be specified via -t path/

### ISSUE THREAD

**Issue by gtx1070rig** [mech2you/Chia#2]
Wo gibt man denn tmpdir1 an?
![tmpdir1](https://user-images.githubusercontent.com/77296186/226804412-336c8814-f946-4117-8aa5-12c53f143d7f.png)

**Comment by mech2you** [comment]
Du musst den MadMax GPU Plotter auswählen und nicht den Chia GPU Plotter ;) Dann sollte es passen.

**Comment by gtx1070rig** [comment]
Ja die neuste Revision von Madmax habe ich - vor 4 Tagen aktualisiert 🤔

**Comment by mech2you** [comment]
![image](https://user-images.githubusercontent.com/61209759/226911460-5e365eb8-6b15-4ec7-8ca8-b0f83bdef237.png)
ändere da auf MadMax GPU Plotter ;)

**Comment by gtx1070rig** [comment]
Alles klar passt ^^
